CoreCorporate/Areas/AdminPanel/Models/AdminRole/AdminRoleAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreCorporate.Areas.AdminPanel.Models.AdminRole
{
    public class AdminRoleAddViewModel
    {
        [Required(ErrorMessage ="Lütfen Yetki Adı Giriniz!")]
        public string Name { get; set; }
    }
}

CoreCorporate/Areas/AdminPanel/Models/AdminRole/AdminRoleAssignViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreCorporate.Areas.AdminPanel.Models.AdminRole
{
    public class AdminRoleAssignViewModel
    {
        public int RoleID { get; set; }
        public string Name { get; set; }
        public bool Exists { get; set; }
    }
}

CoreCorporate/Areas/AdminPanel/Models/AdminRole/AdminRoleUpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreCorporate.Areas.AdminPanel.Models.AdminRole
{
    public class AdminRoleUpdateViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

CoreCorporate/Areas/AdminPanel/Controllers/AdminRoleController.cs
using CoreCorporate.Areas.AdminPanel.Models.AdminRole;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreCorporate.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class AdminRoleController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public AdminRoleController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var values = _roleManager.Roles.ToList();
            return View(values);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(AdminRoleAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppRole role = new AppRole
                {
                    Name = model.Name
                };
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }

            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            AdminRoleUpdateViewModel model = new AdminRoleUpdateViewModel
            {
                Id = values.Id,
                Name = values.Name
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Update(AdminRoleUpdateViewModel model)
        {
            var values = _roleManager.Roles.Where(x => x.Id == model.Id).FirstOrDefault();
            values.Name = model.Name;
            var result = await _roleManager.UpdateAsync(values);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var values = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            var result = await _roleManager.DeleteAsync(values);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult UserRoleList()
        {
            var values = _userManager.Users.ToList();
            return View(values);
        }
        [HttpGet]
        public async Task<IActionResult> AssignRole(int id)
        {
            var user = _userManager.Users.FirstOrDefault(x => x.Id == id);
            var roles = _roleManager.Roles.ToList();

            TempData["UserID"] = user.Id;

            var userRoles = await _userManager.GetRolesAsync(user);
            TempData["UserName"] = user.UserName;

            List<AdminRoleAssignViewModel> model = new List<AdminRoleAssignViewModel>();
            foreach (var item in roles)
            {
                AdminRoleAssignViewModel m = new AdminRoleAssignViewModel();
                m.RoleID = item.Id;
                m.Name = item.Name;
                m.Exists = userRoles.Contains(item.Name);
                model.Add(m);
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(List<AdminRoleAssignViewModel> model)
        {
            var userid = (int)TempData["UserID"];
            var user = _userManager.Users.FirstOrDefault(x => x.Id == userid);
            foreach (var item in model)
            {
                if (item.Exists)
                {
                    await _userManager.AddToRoleAsync(user, item.Name);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, item.Name);
                }
            }
            return RedirectToAction("AssignRole", new { id = userid });
        }

    }
}

CoreCorporate/Areas/AdminPanel/Views/AdminRole/Add.cshtml
@using CoreCorporate.Areas.AdminPanel.Models.AdminRole
@model AdminRoleAddViewModel
@{
    ViewData["Title"] = "Add";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Yeni Yetki Ekle</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Add", "AdminRole", FormMethod.Post))
                            {
                                <div class="form-group">
                                    @Html.Label("Yetki Adı")
                                    <input type="text" asp-for="@Model.Name" class="form-control" />
                                </div>
                                <div class="form-group" asp-validation-summary="ModelOnly">

                                </div>
                                <div>
                                    <button class="btn btn-primary float-right" type="submit"><strong>Yayınla</strong></button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CoreCorporate/Areas/AdminPanel/Views/AdminRole/AssignRole.cshtml
@using CoreCorporate.Areas.AdminPanel.Models.AdminRole
@model List<AdminRoleAssignViewModel>
@{
    ViewData["Title"] = "AssignRole";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
@section styles{
    <link href="~/admintheme/css/plugins/iCheck/custom.css" rel="stylesheet">
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Üye Yetki Düzenleme</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <a href="~/AdminPanel/AdminRole/UserRoleList" class="btn btn-warning btn-sm">Üye Yetki Listesi</a>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("AssignRole", "AdminRole", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Kullanıcı</label>
                                    <input type="text" value="@TempData["UserName"]" class="form-control" disabled>
                                </div>

                                <div class="form-group">
                                    <label>Yetkiler</label>
                                    @for (int i = 0; i < Model.Count; i++)
                                    {
                                        <div class="checkbox i-checks">
                                            <input type="hidden" asp-for="@Model[i].RoleID" />
                                            <input type="hidden" asp-for="@Model[i].Name" />
                                            <input type="checkbox" asp-for="@Model[i].Exists" class="form-check-input" />
                                            <label class="form-check-label" for="@Model[i].Exists">@Model[i].Name</label>
                                        </div>
                                        <br />


                                    }
                                </div>
                                <div>
                                    <button class="btn btn-primary float-right" type="submit"><strong>Güncelle</strong></button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/admintheme/js/plugins/iCheck/icheck.min.js"></script>

    <script>
        $(document).ready(function () {

            $('.custom-file-input').on('change', function () {
                let fileName = $(this).val().split('\\').pop();
                $(this).next('.custom-file-label').addClass("selected").html(fileName);
            });

            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

        });
    </script>

}

CoreCorporate/Areas/AdminPanel/Views/AdminRole/Index.cshtml
@using EntityLayer.Concrete
@model List<AppRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Tüm Yetkiler</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <a href="~/AdminPanel/AdminRole/Add" class="btn btn-primary btn-sm">Yeni Yetki Ekle</a>
                    <a href="~/AdminPanel/AdminRole/UserRoleList" class="btn btn-warning btn-sm">Üye Yetki Listesi</a>
                </div>
                <div class="ibox-content">


                    @if (Model.Count <= 0)
                    {
                        <h2 class="text-center">Henüz yetkiler eklenmemiştir!</h2>
                    }
                    else
                    {
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Yetki Adı</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>
                                            <a href="~/AdminPanel/AdminRole/Update/@item.Id" class="btn btn-w-m btn-primary">Düzenle</a>
                                            <a href="~/AdminPanel/AdminRole/Delete/@item.Id" class="btn btn-w-m btn-danger">Sil</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

CoreCorporate/Areas/AdminPanel/Views/AdminRole/Update.cshtml
@using CoreCorporate.Areas.AdminPanel.Models.AdminRole
@model AdminRoleUpdateViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Yeni Yetki Düzenle</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Update", "AdminRole", FormMethod.Post))
                            {
                                <div class="form-group">
                                    @Html.Label("Yetki Adı")
                                    @Html.HiddenFor(x=>x.Id)
                                    <input type="text" asp-for="@Model.Name" class="form-control" />
                                </div>
                                <div class="form-group" asp-validation-summary="ModelOnly">

                                </div>
                                <div>
                                    <button class="btn btn-primary float-right" type="submit"><strong>Düzenle</strong></button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CoreCorporate/Areas/AdminPanel/Views/AdminRole/UserRoleList.cshtml
@using EntityLayer.Concrete
@model List<AppUser>
@{
    ViewData["Title"] = "UserRoleList";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Üyeler ve Yetkileri</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <a href="~/AdminPanel/AdminRole/Add" class="btn btn-primary btn-sm">Yeni Yetki Ekle</a>
                    <a href="~/AdminPanel/AdminRole/Index" class="btn btn-warning btn-sm">Yetki Listesi</a>
                </div>
                <div class="ibox-content">


                    @if (Model.Count <= 0)
                    {
                        <h2 class="text-center">Henüz sayfa eklenmemiştir!</h2>
                    }
                    else
                    {
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Kullanıcı</th>
                                    <th>Rol Ata</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.UserName</td>
                                        <td><a href="~/AdminPanel/AdminRole/AssignRole/@item.Id" class="btn btn-outline-success">Yetki Ver</a></td>
         
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>